---
- name: Copy mongo repo file to server
  copy:
    src: "{{ playbook_dir }}/scripts/mongodb-org-4.2.repo"
    dest: "/etc/yum.repos.d/"
    mode: '0644'

- name: Install mongodb
  yum:
    name: mongodb-org
    state: present

- name: Install rsync
  yum:
    name: rsync
    state: present

- name: Create DB path and log dir
  file:
    path: "{{ item }}"
    state: directory
    owner: mongod
    group: mongod
    recurse: yes
  with_items:
    - "{{ DB_PATH }}"
    - "{{ LOG_DIR }}"

- name: Create mongo pid file
  file:
    path: "/var/run/mongodb/mongod.pid"
    state: touch
    owner: mongod
    group: mongod

- name: Remove rejecting rule from iptables
  iptables:
    chain: INPUT
    jump: REJECT
    reject_with: icmp-host-prohibited
    state: absent

- name: Open DB port
  firewalld:
    port: "{{ DB_PORT }}/tcp"
    permanent: yes
    state: enabled

- name: Copy mongo conf file to server
  copy:
    src: "{{ playbook_dir }}/scripts/mongod.conf"
    dest: "/etc/"
    mode: '0644'

- name: Configure the /etc/mongod.conf file
  replace:
    path: "/etc/mongod.conf"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.value }}"
  with_items:
    - { regexp: 'LOG_DIR', value: "{{ LOG_DIR }}" }
    - { regexp: 'DB_PATH', value: "{{ DB_PATH }}" }
    - { regexp: 'BIND_IP', value: "{{ BIND_IP }}" }
    - { regexp: 'DB_PORT', value: "{{ DB_PORT }}" }
    - { regexp: 'REPSET_NAME', value: "{{ REPSET_NAME }}" }

- name: Restart mongod service
  service:
    name: mongod
    state: restarted